{{- $nodePathMap := list }}
{{- if .Values.defaultPaths }}
  {{- $nodePathMap = append $nodePathMap (dict "node" "DEFAULT_PATH_FOR_NON_LISTED_NODES" "paths" .Values.defaultPaths) }}
{{- end }}
{{- range $node, $paths := .Values.nodePaths }}
  {{- if $paths }}
    {{- $nodePathMap = append $nodePathMap (dict "node" $node "paths" $paths) }}
  {{- end }}
{{- end }}
{{- if gt (len $nodePathMap) 0 }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: local-path-config
  namespace: kube-system
data:
  config.json: |-
{{ dict "nodePathMap" $nodePathMap | toPrettyJson | indent 4 }}
  setup: |-
    #!/bin/sh
    set -eu
    mkdir -m 0777 -p "${VOL_DIR}"
    chmod 777 "${VOL_DIR}/.."
  teardown: |-
    #!/bin/sh
    set -eu
    rm -rf "${VOL_DIR}"
  helperPod.yaml: |-
    apiVersion: v1
    kind: Pod
    metadata:
      name: helper-pod
    spec:
      containers:
      - name: helper-pod
        image: "rancher/mirrored-library-busybox:1.36.1"
        imagePullPolicy: IfNotPresent
{{- end }}
