
{{- if .Values.awsParameterStore.enable }}
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-ssm-parameter-store-argocd-avp
spec:
  provider:
    aws:
      service: ParameterStore
      region: "{{ .Values.awsParameterStore.region }}"
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: "{{ .Values.awsParameterStore.iamSecretRef.name }}"
            key: access-key
            namespace: "{{ .Values.awsParameterStore.iamSecretRef.namespace | default .Release.Namespace}}"
          secretAccessKeySecretRef:
            name: "{{ .Values.awsParameterStore.iamSecretRef.name }}"
            key: secret-access-key
            namespace: "{{ .Values.awsParameterStore.iamSecretRef.namespace | default .Release.Namespace }}"
{{- end }}