apiVersion: v2
name: cloudflare-tunnel-remote
description: A Helm chart with cloudflare-tunnel-remote as subchart
version: 1.1.0
maintainers:
  - name: komailo
    url: https://github.com/komailo/helm-charts
sources:
  - https://github.com/komailo/helm-charts
dependencies:
  - name: cloudflare-tunnel-remote
    version: "0.1.2"
    repository: https://cloudflare.github.io/helm-charts
    alias: cloudflare-tunnel-remote
    condition: cloudflare-tunnel-remote.enabled
