---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-nginx
  namespace: "{{ .Release.Namespace }}"
spec:
  secretName: ingress-nginx-tls
  dnsNames:
    - ingress-nginx.{{ .Values.clusterDomain }}
  issuerRef:
    name: "{{ .Values.certManagerClusterIssuer}}"
    kind: ClusterIssuer
