apiVersion: v2
name: traefik
description: A Helm chart with traefik as subchart
type: application
version: 3.0.0

maintainers:
  - name: komailo
    url: https://github.com/komailo/helm-charts
sources:
  - https://github.com/komailo/helm-charts
dependencies:
  - name: traefik
    version: "39.0.0"
    repository: oci://ghcr.io/traefik/helm
    condition: traefik.enabled
