clusterDomain: ~
certManagerClusterIssuer: ~
ingress-nginx:
  controller:
    config:
      proxy-real-ip-cidr: "0.0.0.0/0"
    service:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: ~
    extraArgs:
      default-ssl-certificate: "ingress-nginx-tls"
