apiVersion: v2
name: librechat
description: A Helm chart with librechat as subchart
type: application
version: 1.1.0

maintainers:
  - name: komailo
    url: https://github.com/komailo/helm-charts
sources:
  - https://github.com/komailo/helm-charts
dependencies:
  - name: librechat
    version: "1.9.5"
    repository: oci://ghcr.io/danny-avila/librechat-chart
    condition: librechat.enabled
  - name: external-secrets-manager
    version: "1.1.0"
    repository: https://komailo.github.io/helm-charts
    condition: external-secrets-manager.enabled
    alias: esm
