{{- if .Values.SimpleSecrets -}}
{{- include "external-secret-manager.simple" . -}}
{{- end -}}

{{- if .Values.SubPathSecrets -}}
{{- include "external-secret-manager.subpath" . -}}
{{- end -}}

{{- if .Values.JsonSecrets -}}
{{- include "external-secret-manager.json" . -}}
{{- end -}}
