SimpleSecrets:
  - name: dns-token
    dataSecretKey: token
    remoteRefKey: /blah/external-dns/dns-token

SubPathSecrets:
  - name: backup-secrets
    remoteRefKey: /k8s-dev/backup

DotEnvSecrets:
  - name: app-env
    remoteRefKey: /k8s/env/app
