{{- if not .Values.argoRollout }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-{{ .Release.Name }}-deployment
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: whoami-{{ .Release.Name }}
  template:
    metadata:
      labels:
        app: whoami-{{ .Release.Name }}
    spec:
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          name: whoami-{{ .Release.Name }}
          ports:
            - containerPort: 80
{{- end }}
